---
# This playbook deploys a simple kubeadm install.
- name: Bootstrap Tasks
  hosts: all
  remote_user: ansible
  gather_facts: False
  roles:
    - common

- name: Install Kubernetes master
  hosts: master
  remote_user: ansible
  become: yes
  become_method: sudo
  roles:
    - docker
    - kubeadm
    - master

- name: Install nodes
  remote_user: ansible
  hosts: worker
  become: yes
  become_method: sudo
  roles:
    - docker
    - kubeadm
    - worker
