---

- name: install transport-https
  apt: package={{ item }} update_cache=yes
  with_items:
    - apt-transport-https

- apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    state: present

- name: add kubernetes repo
  command: touch /etc/apt/sources.list.d/kubernetes.list
- lineinfile: dest="/etc/apt/sources.list.d/kubernetes.list" line="{{item}}"
  with_items:
    - "deb http://apt.kubernetes.io/ kubernetes-xenial main"

- name: install kubeadm
  apt: package={{ item }}  update_cache=yes
  with_items:
    - kubelet
    - kubeadm
    - kubectl
    - kubernetes-cni

# Download portmap because kubernetes-cni does not include but flannel needs
- name: download portmap
  get_url:
        url: https://github.com/projectcalico/cni-plugin/releases/download/v1.9.1/portmap
        dest: /opt/cni/bin/portmap
        mode: 0755