---

- name: kubeadm init with pre generated token
  command: kubeadm init --pod-network-cidr {{ flannel_subnet }} --token {{ kubeadm_token }}

- pause:
    minutes: 3
    prompt: "Make sure admin pods are started"

- name: allow permissive RBAC rules
  command: "kubectl --kubeconfig /etc/kubernetes/admin.conf create clusterrolebinding permissive-binding \
  --clusterrole=cluster-admin \
  --user=admin \
  --user=kubelet \
  --group=system:serviceaccounts"

- name: taint master node
  command: kubectl --kubeconfig /etc/kubernetes/admin.conf taint nodes --all node-role.kubernetes.io/master-

- name: install flannel pod network
  command: kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

- name: copy config file to HOME dir
  command: "{{ item }}"
  with_items:
    - cp /etc/kubernetes/admin.conf ~{{ansible_remote_user }}/admin.conf
    - chown {{ ansible_remote_user }}:{{ ansible_remote_user }} ~{{ansible_remote_user }}/admin.conf
    - chmod 0400 ~{{ansible_remote_user }}/admin.conf

- name: write KUBECONFGIG to bashrc
  lineinfile: dest="~{{ansible_remote_user }}/.bashrc" line="{{item}}"
  with_items:
     - "export KUBECONFIG=$HOME/admin.conf"

- pause:
    minutes: 3
    prompt: "Make sure network pods are started"